app:
  name: Golang_starter
  debug: true

server: 
  address: 9090

context:
  timeout: 2

mongo: 
  host: localhost
  port: 27017
  user: 
  pass: 
  name: golang_starter

jwt:
  secret: JwtSecretBroh
  lifetime: 60

admin:
  username: vian
  password: 12345678
