// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo"
	mock "github.com/stretchr/testify/mock"
)

// JwtUsecase is an autogenerated mock type for the JwtUsecase type
type JwtUsecase struct {
	mock.Mock
}

// SetJwtAdmin provides a mock function with given fields: g
func (_m *JwtUsecase) SetJwtAdmin(g *echo.Group) {
	_m.Called(g)
}

// SetJwtGeneral provides a mock function with given fields: g
func (_m *JwtUsecase) SetJwtGeneral(g *echo.Group) {
	_m.Called(g)
}

// SetJwtUser provides a mock function with given fields: g
func (_m *JwtUsecase) SetJwtUser(g *echo.Group) {
	_m.Called(g)
}
