// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/bxcodec/go-clean-arch/domain"
	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// FindOne provides a mock function with given fields: ctx, id
func (_m *UserRepository) FindOne(ctx context.Context, id string) (*domain.User, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.User
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllWithPage provides a mock function with given fields: ctx, rp, p, filter, setsort
func (_m *UserRepository) GetAllWithPage(ctx context.Context, rp int64, p int64, filter interface{}, setsort interface{}) ([]domain.User, int64, error) {
	ret := _m.Called(ctx, rp, p, filter, setsort)

	var r0 []domain.User
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, interface{}, interface{}) []domain.User); ok {
		r0 = rf(ctx, rp, p, filter, setsort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}

	var r1 int64
	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, interface{}, interface{}) int64); ok {
		r1 = rf(ctx, rp, p, filter, setsort)
	} else {
		r1 = ret.Get(1).(int64)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, int64, int64, interface{}, interface{}) error); ok {
		r2 = rf(ctx, rp, p, filter, setsort)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByCredential provides a mock function with given fields: ctx, username, password
func (_m *UserRepository) GetByCredential(ctx context.Context, username string, password string) (*domain.User, error) {
	ret := _m.Called(ctx, username, password)

	var r0 *domain.User
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = rf(ctx, username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertOne provides a mock function with given fields: ctx, u
func (_m *UserRepository) InsertOne(ctx context.Context, u *domain.User) (*domain.User, error) {
	ret := _m.Called(ctx, u)

	var r0 *domain.User
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) *domain.User); ok {
		r0 = rf(ctx, u)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.User) error); ok {
		r1 = rf(ctx, u)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOne provides a mock function with given fields: ctx, user, id
func (_m *UserRepository) UpdateOne(ctx context.Context, user *domain.User, id string) (*domain.User, error) {
	ret := _m.Called(ctx, user, id)

	var r0 *domain.User
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User, string) *domain.User); ok {
		r0 = rf(ctx, user, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.User, string) error); ok {
		r1 = rf(ctx, user, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
